name: Gradle Pandoc Plugin
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Pull image
      run: docker pull pandoc/latex:latest
    - name: Build
      run: ./gradlew build
    - name: Test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Gradle Tests
        path: build/test-results/test/*.xml
        reporter: java-junit