name: Gradle Pandoc Plugin
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17 ]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Gradle Tests
        path: build/test-results/test/*.xml
        reporter: java-junit
    - name: Release
      uses: gradle/gradle-build-action@v2
      with:
        arguments: release